chouette11/wordwolf

lib/page/chat/component/bottom_text_field.dart, lib/repository/message_repository.dart
送信ボタンを押したときにFirestoreに保存されるようにした。
=> 送信ボタンを押したときの関数実装

lib/page/chat/component/bottom_text_field.dart, lib/page/chat/component/receive_message_bubble.dart, lib/page/root/component/join_dialog.dart, lib/page/root/component/start_dialog.dart, lib/page/root/root_page.dart
Display the ID input dialog when you press "参加する".
=> rootPageの作成

lib/data/api/gpt_api.dart, lib/data/api/gpt_api.g.dart, lib/data/api_data_source.dart, lib/entity/task/message_entity.dart, lib/entity/task/message_entity.freezed.dart, lib/entity/task/message_entity.g.dart, lib/page/chat/chat_page.dart, lib/repository/message_repository.dart, pubspec.lock, pubspec.yaml
サンプルapiにPOSTリクエストを送信し、そのレスポンスをfirestoreに保存して表示した。
=> apiの実装を行った

lib/page/chat/component/join_dialog.dart, lib/page/root/root_page.dart, lib/provider/presentation_providers.dart
=> 回答のダイアログを実装した

lib/page/chat/chat_page.dart, lib/page/chat/component/answer_dialog.dart, lib/page/chat/component/correct_dialog.dart
=> 正解の表示ダイアログを追加した

lib/data/firestore_data_source.dart, lib/page/root/component/join_dialog.dart, lib/provider/presentation_providers.dart, lib/repository/room_repository.dart
roomが作成されていないときに、そのルームに参加するとuserIdが割り当てられずにエラーが表示されるので、入力したidのルームが存在していない場合、参加ができないようにした。
=> ルームが作成してないと参加できないようにした

lib/page/chat/chat_page.dart, lib/page/chat/component/answer_dialog.dart, lib/page/chat/component/correct_dialog.dart, lib/page/root/root_page.dart
ゲームを終了するダイアログの文字が定数であったのを変数に変更してフローを作成した。
=> ゲームを終了するフローを作成した

lib/page/chat/chat_page.dart
=> appbarにroomidを表示

lib/data/firestore_data_source.dart, lib/page/chat/chat_page.dart, lib/page/chat/component/answer_dialog.dart, lib/page/chat/component/correct_dialog.dart, lib/repository/room_repository.dart
ルームが被るのを防ぐために、ルームを削除する機能を実装した。
終了時にrooms/{roomId}/membersから削除し、その配列がemptyの場合ルームを削除した。
=> ゲームを終了したときにルームを削除

lib/page/root/root_page.dart
WillPopScopeによってゲーム終了後にRootPageに戻らないようにした
=> ゲーム終了後にRootPageに戻らないようにした。

lib/page/root/component/start_dialog.dart, lib/provider/presentation_providers.dart, pubspec.lock, pubspec.yaml
=> 参加人数を選べるようにした

lib/page/chat/chat_page.dart, lib/page/chat/component/bottom_field.dart
=> タイムアップ後、bottomsheetを変換

lib/page/chat/chat_page.dart, lib/page/chat/component/theme_dialog.dart
=> 参加を押した時に、最初の解答を入力するダイアログ表示

lib/data/firestore_data_source.dart, lib/entity/room/room_entity.dart, lib/page/chat/chat_page.dart, lib/page/chat/component/theme_dialog.dart, lib/page/root/component/start_dialog.dart, lib/provider/presentation_providers.dart, lib/repository/room_repository.dart
close #47 
- maxNumの反映
- maxNumから0を取り除いた
- maxNumにgptの分を追加した
- 全員がお題に対して回答(roomのmessagesの数がmaxNumと一致)するまで、文字を表示し、ボタンを押せなくした
-
=> お題に全員が回答するまで待つようにした

lib/page/chat/chat_page.dart, lib/page/chat/component/correct_dialog.dart, lib/page/root/component/start_dialog.dart, lib/provider/presentation_providers.dart
isMakeRoomProviderを作成し、部屋の作成者のみがgptにリクエストを送るようにした
=> 部屋の作成者のみがgptにリクエストを送るようにした

lib/page/chat/chat_page.dart, lib/page/chat/component/theme_dialog.dart, lib/repository/message_repository.dart
close #62 
今までの場合、gptの返答が一番上に来ていたので、リクエストのタイミングを変更し、2番目や3番目に来るようにした。
=> topicに対するgptの返答の時間に揺れを与えた

lib/page/root/component/join_dialog.dart
=> textfieldの色変更

lib/page/root/component/start_dialog.dart
=> コピーと共有のボタンデザイン変更

lib/page/chat/component/receive_message_bubble.dart
=> 相手のユーザーのアイコンを作成した

android/app/build.gradle, android/app/google-services.json, android/app/src/main/kotlin/com/knockAI/MainActivity.kt, lib/firebase_options.dart, pubspec.yaml
close #72 
Androidのリリース(0.1.0)をした。
https://gakogako.com/flutter_android_release/
=> Androidのリリースをした

lib/document/member/member_document.dart, lib/document/member/member_document.freezed.dart, lib/document/member/member_document.g.dart, lib/document/room/room_document.dart, lib/document/room/room_document.freezed.dart, lib/document/room/room_document.g.dart, lib/entity/member/member_entity.dart, lib/entity/member/member_entity.freezed.dart, lib/entity/room/room_entity.dart, lib/entity/room/room_entity.freezed.dart, lib/entity/room/room_entity.g.dart, lib/page/chat/component/bottom_text_field.dart, lib/page/chat/component/role_dialog.dart, lib/provider/presentation_providers.g.dart, lib/repository/room_repository.dart
役職の割り当てを行った。
- member modelにroleの追加
- room modelからmembersの削除、rolesの追加
=> 役職の割り当てを行った

lib/page/chat/component/role_dialog.dart
=> roleDialogのUI変更

lib/page/chat/component/end_dialog.dart
=> endDesignのUI改修

lib/page/chat/component/executed_dialog.dart
=> excutedDialogのデザイン改修

lib/data/firestore_data_source.dart, lib/page/chat/component/bottom_text_field.dart, lib/page/chat/component/died_dialog.dart, lib/page/chat/component/end_dialog.dart, lib/provider/presentation_providers.dart, lib/provider/presentation_providers.g.dart, lib/repository/room_repository.dart, pubspec.yaml
=> ユーザが死んだ時のUI作成

lib/page/chat/chat_page.dart, lib/page/chat/component/answer_dialog.dart, lib/page/night/night_page.dart, lib/page/root/component/join_dialog.dart, lib/provider/presentation_providers.dart, lib/repository/member_repository.dart, lib/repository/room_repository.dart
close #111 
- MemberRepositoryの作成
- isLimitMemberの作成
=> 満室の場合入れないようにした

lib/document/room/room_document.dart, lib/document/room/room_document.freezed.dart, lib/document/room/room_document.g.dart, lib/entity/room/room_entity.dart, lib/entity/room/room_entity.freezed.dart, lib/entity/room/room_entity.g.dart, lib/page/chat/chat_page.dart, lib/page/chat/component/bottom_text_field.dart, lib/page/chat/component/chat_appbar.dart, lib/page/chat/component/theme_dialog.dart, lib/provider/presentation_providers.dart, lib/repository/message_repository.dart, lib/repository/room_repository.dart
topicを部屋で管理し、FutureProviderで管理するようにした。
- room modelにtopic の引数追加
- topicをStateProviderからFutureProviderに変更
=> トピックを部屋で管理するようにした

lib/data/firestore_data_source.dart, lib/document/room/room_document.dart, lib/document/room/room_document.freezed.dart, lib/document/room/room_document.g.dart, lib/entity/member/member_entity.dart, lib/entity/member/member_entity.freezed.dart, lib/entity/room/room_entity.dart, lib/entity/room/room_entity.freezed.dart, lib/entity/room/room_entity.g.dart, lib/page/chat/chat_page.dart, lib/page/chat/component/receive_message_bubble.dart, lib/page/night/night_page.dart, lib/provider/presentation_providers.dart, lib/repository/member_repository.dart, lib/repository/room_repository.dart
- room modelにkilledIdを追加した
- randomKillの関数を編集した
- assignedIdをStringからintに変更した
=> ルームで殺害された人を管理し、フリーズバグを修正した

lib/page/root/component/join_dialog.dart, lib/page/root/component/make_dialog.dart, lib/page/start/make_room_page.dart, lib/provider/domain_providers.dart
url経由か正当かを判別して、makeRoomでwebがJoinするか決めた
=> webのJoinを変更した
